# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Qian Liu
title: PhD Candidate
email: qian.liu at buaa.edu.cn
website: http://cnblogs.com/SivilTaram

# Social links
# twitter_username: facespics
github_username:  SivilTaram
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: siviltaram
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Qian.

  I am most skilled in: <mark>Natural Lnaugage Processing</mark> and <mark>Semantic Parsing</mark> and <mark>Conversation</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  # Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #  - Rock climbing
  #  - Gaming
  #  - Knitting
  #  - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
